CREATE TABLE EVENT (
 
 TITLE TEXT NOT NULL UNIQUE,
 START_DATE DATE NOT NULL,
 END_DATE DATE NOT NULL,
 START_TIME TIME NOT NULL,
 END_TIME TIME NOT NULL,
 LOCATION TEXT NOT NULL,
 PRIMARY KEY(TITLE)
);

CREATE TABLE USER (
 ID SERIAL,
 USERNAME TEXT NOT NULL,
 FIRST TEXT NOT NULL,
 LAST TEXT NOT NULL,
 PRIMARY KEY(ID, USERNAME)
);